SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET foreign_key_checks=0;
TRUNCATE TABLE ciclos;
START TRANSACTION;

INSERT INTO `ciclos` (`codCiclo`, `codFamilia`, `nombre`, `grado`) VALUES
('ACEC2', 'ADG', 'Técnico en Actividades Ecuestres', 'G.M.'),
('ACFI3', 'ADG', 'Técnico Superior en Acondicionamiento Físico', 'G.S.'),
('ACID1', 'ADG', 'Profesional Básico en Acceso y Conservación en Instalaciones Deportivas', 'BÁSICA'),
('EASO3', 'ADG', 'Técnico Superior en Enseñanza y Animación Sociodeportiva', 'G.S.'),
('GMTL2', 'ADG', 'Técnico en Guía en el Medio Natural y de Tiempo Libre', 'G.M.'),
('ADFI3', 'AFD', 'Técnico Superior en Administración y Finanzas', 'G.S.'),
('ASDI3', 'AFD', 'Técnico Superior en Asistencia a la Dirección', 'G.S.'),
('GADM2', 'AFD', 'Técnico en Gestión Administrativa', 'G.M.'),
('INOF1', 'AFD', 'Profesional Básico en Informática de Oficina', 'BÁSICA'),
('SEAD1', 'AFD', 'Profesional Básico en Servicios Administrativos', 'BÁSICA'),
('ACAG1', 'AGA', 'Profesional Básico en Actividades Agropecuarias', 'BÁSICA'),
('ACEC2', 'AGA', 'Técnico en Actividades Ecuestres', 'G.M.'),
('ACMN2', 'AGA', 'Técnico en Aprovechamiento y Conservación del Medio Natural', 'G.M.'),
('AGCO1', 'AGA', 'Profesional Básico en Agro-jardinería y Composiciones Florales', 'BÁSICA'),
('APFO1', 'AGA', 'Profesional Básico en Aprovechamientos Forestales', 'BÁSICA'),
('GASA3', 'AGA', 'Técnico Superior en Ganadería y Asistencia en Sanidad Animal', 'G.S.'),
('GFMN3', 'AGA', 'Técnico Superior en Gestión Forestal y del Medio Natural', 'G.S.'),
('JAFO2', 'AGA', 'Técnico en Jardinería y Floristería', 'G.M.'),
('PAMR3', 'AGA', 'Técnico Superior en Paisajismo y Medio Rural', 'G.S.'),
('PRAE2', 'AGA', 'Técnico en Producción Agroecológica', 'G.M.'),
('PRAP2', 'AGA', 'Técnico en Producción Agropecuaria', 'G.M.'),
('ARFA3', 'ARA', 'Técnico Superior en Artista Fallero y Construcción de Escenografías', 'G.S.'),
('ARGR1', 'ARG', 'Profesional Básico en Artes Gráficas', 'BÁSICA'),
('DEPM3', 'ARG', 'Técnico superior en Diseño y Edición de Publicaciones Impresas y Multimedia', 'G.S.'),
('DGPG3', 'ARG', 'Técnico Superior en Diseño y Gestión de la Producción Gráfica', 'G.S.'),
('IMGR2', 'ARG', 'Técnico en Impresión Gráfica', 'G.M.'),
('PIAG2', 'ARG', 'Técnico Post-impresión y Acabados Gráficos', 'G.M.'),
('PRID2', 'ARG', 'Técnico en Pre-impresión Digital', 'G.M.'),
('ACCO2', 'COM', 'Técnico en Actividades Comerciales', 'G.M.'),
('COIN3', 'COM', 'Técnico Superior en Comercio Internacional', 'G.S.'),
('COPA2', 'COM', 'Técnico en Comercialización de Productos Alimentarios', 'G.M.'),
('GVEC3', 'COM', 'Técnico Superior en Gestión de Ventas y Espacios Comerciales', 'G.S.'),
('MAPU3', 'COM', 'Técnico Superior en Marketing y Publicidad', 'G.S.'),
('SECO1', 'COM', 'Profesional Básico en Servicios Comerciales', 'BÁSICA'),
('TRLO3', 'COM', 'Técnico Superior en Transporte y Logística', 'G.S.'),
('AURI3', 'ELE', 'Técnico Superior en Automatización y Robótica Industrial', 'G.S.'),
('CIOP3', 'ELE', 'Curso de Especialización en Ciberseguridad en Entornos de las Tecnologías de Operación', 'C.E. (G.S.)'),
('CIOT2', 'ELE', 'Conectados a Internet (IoT)', 'C.E. (G.M.)'),
('ELEL1', 'ELE', 'Profesional Básico en Electricidad y Electrónica', 'BÁSICA'),
('EMCL3', 'ELE', 'Técnico Superior en Electromedicina Clínica', 'G.S.'),
('FAEM1', 'ELE', 'Profesional Básico en Fabricación de Elementos Metálicos', 'BÁSICA'),
('IEME1', 'ELE', 'Profesional Básico en Instalaciones Electrotécnicas y Mecánica', 'BÁSICA'),
('IMSC2', 'ELE', 'Curso de Especialización en Instalación y Mantenimiento de Sistemas', 'C.E. (G.M.)'),
('INEA2', 'ELE', 'Técnico en Instalaciones Eléctricas y Automáticas', 'G.M.'),
('INTE2', 'ELE', 'Técnico en Instalaciones de Telecomunicaciones', 'G.M.'),
('IREG2', 'ELE', 'Curso de Especialización en Implementación de Redes 5G', 'C.E. (G.M.)'),
('MAEL3', 'ELE', 'Técnico Superior en Mantenimiento Electrónico', 'G.S.'),
('ROCO3', 'ELE', 'Curso de Especialización en Robótica Colaborativa', 'C.E. (G.S.)'),
('SELA3', 'ELE', 'Técnico Superior en Sistemas Electrotécnicos y Automatizados', 'G.S.'),
('SITF3', 'ELE', 'Curso de Especialización en Sistemas de Señalización y Telecomunicaciones Ferroviarias', 'C.E. (G.S.)'),
('STEI3', 'ELE', 'Técnico Superior en Sistemas de Telecomunicaciones e Informáticos', 'G.S.'),
('AUEN3', 'ENA', 'Curso de Especialización en Auditoría Energética', 'C.E. (G.S.)'),
('CEEL3', 'ENA', 'Técnico Superior en Centrales Eléctricas', 'G.S.'),
('EEST3', 'ENA', 'Técnico Superior en Eficiencia Energética y Energía Solar Térmica', 'G.S.'),
('ENRE3', 'ENA', 'Técnico Superior en Energías Renovables', 'G.S.'),
('GEAG3', 'ENA', 'Técnico Superior en Gestión del Agua', 'G.S.'),
('REAG2', 'ENA', 'Técnico en Redes y Estaciones de Tratamiento de Agua', 'G.M.'),
('CONS2', 'EOC', 'Técnico en Construcción', 'G.M.'),
('OCOC3', 'EOC', 'Técnico Superior en Organización y Control de Obras de Construcción', 'G.S.'),
('OIDR2', 'EOC', 'Técnico en Obras de Interior, Decoración y Rehabilitación', 'G.M.'),
('PRED3', 'EOC', 'Técnico Superior en Proyectos de Edificación', 'G.S.'),
('PROC3', 'EOC', 'Técnico Superior en Proyectos de Obra Civil', 'G.S.'),
('REMA1', 'EOC', 'Profesional Básico en Reforma y Mantenimiento de Edificios', 'BÁSICA'),
('CMMP2', 'FME', 'Técnico en Conformado por Moldeo de Metales y Polímeros', 'G.M.'),
('COME3', 'FME', 'Técnico Superior en Construcciones Metálicas', 'G.S.'),
('DIFM3', 'FME', 'Técnico Superior en Diseño en Fabricación Mecánica', 'G.S.'),
('FAAD3', 'FME', 'Curso de Especialización en Fabricación Aditiva', 'C.E. (G.S.)'),
('FAEM1', 'FME', 'Profesional Básico en Fabricación de Elementos Metálicos', 'BÁSICA'),
('FAMO1', 'FME', 'Profesional Básico en Fabricación y Montaje', 'BÁSICA'),
('IEME1', 'FME', 'Profesional Básico en Instalaciones Electrotécnicas y Mecánica', 'BÁSICA'),
('MCIA3', 'FME', 'Curso de Especialización en Materiales Compuestos en la Industria Aeroespacial', 'C.E. (G.S.)'),
('MECA2', 'FME', 'Técnico en Mecanizado', 'G.M.'),
('MESA2', 'FME', 'Técnico en Montaje de Estructuras e Instalación de Sistemas Aeronáuticos', 'G.M.'),
('PPFM3', 'FME', 'Técnico Superior en Programación de la Producción en Fabricación Mecánica', 'G.S.'),
('PPMP3', 'FME', 'Técnico Superior en Programación de la Producción en Moldeo de Metales y Polímeros', 'G.S.'),
('SOCA2', 'FME', 'Técnico en Soldadura y Calderería', 'G.M.'),
('ALLA1', 'HOT', 'Profesional Básico en Alojamiento y Lavandería', 'BÁSICA'),
('AVGE3', 'HOT', 'Técnico Superior en Agencias de Viajes y Gestión de Eventos', 'G.S.'),
('COGA2', 'HOT', 'Técnico en Cocina y Gastronomía', 'G.M.'),
('COPA2', 'HOT', 'Técnico en Comercialización de Productos Alimentarios', 'G.M.'),
('CORE1', 'HOT', 'Profesional Básico en Cocina y Restauración', 'BÁSICA'),
('DICO3', 'HOT', 'Técnico Superior en Dirección de Cocina', 'G.S.'),
('DISR3', 'HOT', 'Técnico Superior en Dirección de Servicios de Restauración', 'G.S.'),
('GEAT3', 'HOT', 'Técnico Superior en Gestión de Alojamientos Turísticos', 'G.S.'),
('GIAT3', 'HOT', 'Técnico Superior en Guía, Información y Asistencias Turísticas', 'G.S.'),
('PABA2', 'HOT', 'Curso de Especialización en Panadería y Bollería Artesanales', 'C.E. (G.M.)'),
('PAPA1', 'HOT', 'Profesional Básico en Actividades de Panadería y Pastelería', 'BÁSICA'),
('SERE2', 'HOT', 'Técnico en Servicios de Restauración', 'G.M.'),
('EXSO2', 'IEX', 'Técnico en Excavaciones y Sondeos', 'G.M.'),
('PINA2', 'IEX', 'Técnico en Piedra Natural', 'G.M.'),
('ASIR3', 'IFC', 'Técnico Superior en Administración de Sistemas Informáticos en Red', 'G.S.'),
('CIIN3', 'IFC', 'Curso de Especialización en Ciberseguridad en Entornos de las Tecnologías de la Información', 'C.E. (G.S.)'),
('DAPM3', 'IFC', 'Técnico Superior en Desarrollo de Aplicaciones Multiplataforma', 'G.S.'),
('DAPW3', 'IFC', 'Técnico Superior en Desarrollo de Aplicaciones Web', 'G.S.'),
('DVRV3', 'IFC', 'Curso de Especialización en Desarrollo de Videojuegos y Realidad Virtual', 'C.E. (G.S.)'),
('IABD3', 'IFC', 'Curso de Especialización en Inteligencia Artificial y Big Data', 'C.E. (G.S.)'),
('INCO1', 'IFC', 'Profesional Básico en Informática y Comunicaciones', 'BÁSICA'),
('INOF1', 'IFC', 'Profesional Básico en Informática de Oficina', 'BÁSICA'),
('SMIR2', 'IFC', 'Técnico en Sistemas Microinformáticos y Redes', 'G.M.'),
('DIMI3', 'IMA', 'Curso de Especialización en Digitalización del Mantenimiento Industrial', 'C.E. (G.S.)'),
('DPTF3', 'IMA', 'Técnico Superior en Desarrollo de Proyectos de Instalaciones Térmicas y de Fluidos', 'G.S.'),
('FAIN3', 'IMA', 'Curso de Especialización en Fabricación Inteligente', 'C.E. (G.S.)'),
('FAMO1', 'IMA', 'Profesional Básico en Fabricación y Montaje', 'BÁSICA'),
('INFC2', 'IMA', 'Técnico en Instalaciones Frigoríficas y de Climatización', 'G.M.'),
('INPC2', 'IMA', 'Técnico en Instalaciones de Producción de Calor', 'G.M.'),
('MAEL2', 'IMA', 'Técnico en Mantenimiento Electromecánico', 'G.M.'),
('MAVI1', 'IMA', 'Profesional Básico en Mantenimiento de Viviendas', 'BÁSICA'),
('MEIN3', 'IMA', 'Técnico Superior en Mecatrónica Industrial', 'G.S.'),
('MITF3', 'IMA', 'Técnico Superior en Mantenimiento de Instalaciones Térmicas y de Fluidos', 'G.S.'),
('MOIN3', 'IMA', 'Curso de Especialización en Modelado de la Información en la Construcción (BIM)', 'C.E. (G.S.)'),
('AIPC3', 'IMP', 'Técnico Superior en Asesoría de Imagen Personal y Corporativa', 'G.S.'),
('CMPR3', 'IMP', 'Técnico Superior en Caracterización y Maquillaje Profesional', 'G.S.'),
('EDPE3', 'IMP', 'Técnico Superior en Estilismo y Dirección de Peluquería', 'G.S.'),
('ESBE2', 'IMP', 'Técnico en Estética y Belleza', 'G.M.'),
('ESIB3', 'IMP', 'Técnico Superior en Estética Integral y Bienestar', 'G.S.'),
('PCNC2', 'IMP', 'Técnico en Peluquería y Cosmética Capilar', 'G.M.'),
('PEES1', 'IMP', 'Profesional Básico en Peluquería y Estética', 'BÁSICA'),
('TEBI3', 'IMP', 'Técnico Superior en Termalismo y Bienestar', 'G.S.'),
('AJEI3', 'IMS', 'Técnico Superior en Animación 3D, Juegos y Entornos Interactivos', 'G.S.'),
('AUSU3', 'IMS', 'Curso de Especialización en Audiodescripción y Subtitulación', 'C.E. (G.S.)'),
('ICTI3', 'IMS', 'Técnico Superior en Iluminación, Captación y Tratamiento de Imagen', 'G.S.'),
('PAES3', 'IMS', 'Técnico Superior en Producción de Audiovisuales y Espectáculos', 'G.S.'),
('RAES3', 'IMS', 'Técnico Superior en Realización de Proyectos Audiovisuales y Espectáculos', 'G.S.'),
('SAES3', 'IMS', 'Técnico Superior en Sonido para Audiovisuales y Espectáculos', 'G.S.'),
('VDJS2', 'IMS', 'Técnico en Video Disc-jockey y Sonido', 'G.M.'),
('ACOV2', 'INA', 'Técnico en Aceites de Oliva y Vinos', 'G.M.'),
('ELPA2', 'INA', 'Técnico en Elaboración de Productos Alimenticios', 'G.M.'),
('INAL1', 'INA', 'Profesional Básico en Industrias Alimentarias', 'BÁSICA'),
('PAPA1', 'INA', 'Profesional Básico en Actividades de Panadería y Pastelería', 'BÁSICA'),
('PARC2', 'INA', 'Técnico en Panadería, Repostería y Confitería', 'G.M.'),
('PCIA3', 'INA', 'Técnico Superior en Procesos y Calidad en la Industria Alimentaria', 'G.S.'),
('VITI3', 'INA', 'Técnico en Vitivinicultura', 'G.S.'),
('CAMU1', 'MAM', 'Profesional Básico en Carpintería y Mueble', 'BÁSICA'),
('CAMU2', 'MAM', 'Técnico en Carpintería y Mueble', 'G.M.'),
('DIAM3', 'MAM', 'Técnico Superior en Diseño y Amueblamiento', 'G.S.'),
('INAM2', 'MAM', 'Técnico en Instalación y Amueblamiento', 'G.M.'),
('PTMA2', 'MAM', 'Técnico en Procesado y Transformación de la Madera', 'G.M.'),
('ACMA1', 'MAP', 'Profesional Básico en Actividades Marítimo-Pesqueras', 'BÁSICA'),
('ACUI3', 'MAP', 'Técnico Superior en Acuicultura', 'G.S.'),
('CUAC2', 'MAP', 'Técnico en Cultivos Acuícolas', 'G.M.'),
('MCMB2', 'MAP', 'Técnico en Mantenimiento y Control de la Maquinaria de Buques y Embarcaciones', 'G.M.'),
('MEDR1', 'MAP', 'Profesional Básico en Mantenimiento de Embarcaciones Deportivas y de Recreo', 'BÁSICA'),
('NPLI2', 'MAP', 'Técnico en Navegación y Pesca de Litoral', 'G.M.'),
('OMMB3', 'MAP', 'Técnico Superior en Organización del Mantenimiento de Maquinaria de Buques y Embarcaciones', 'G.S.'),
('OSHI2', 'MAP', 'Técnico en Operaciones Subacuáticas e Hiperbáricas', 'G.M.'),
('TMPA3', 'MAP', 'Técnico Superior en Transporte Marítimo y Pesca de Altura', 'G.S.'),
('CUCE3', 'QUI', 'Curso de Especialización en Cultivos Celulares', 'C.E. (G.S.)'),
('FPFB3', 'QUI', 'Técnico Superior en Fabricación de Productos Farmacéuticos, Biotecnológicos y Afines', 'G.S.'),
('LACC3', 'QUI', 'Técnico Superior en Laboratorio de Análisis y de Control de Calidad', 'G.S.'),
('OPLA2', 'QUI', 'Técnico en Operaciones de Laboratorio', 'G.M.'),
('PLQI2', 'QUI', 'Técnico en Planta Química', 'G.M.'),
('QUIN3', 'QUI', 'Técnico Superior en Química Industrial', 'G.S.'),
('ANPAC3', 'SAN', 'Técnico Superior en Anatomía Patológica y Citodiagnóstico', 'G.S.'),
('AUPR3', 'SAN', 'Técnico Superior en Audiología Protésica', 'G.S.'),
('DADSA3', 'SAN', 'Técnico Superior en Documentación y Administración Sanitarias', 'G.S.'),
('EMSA2', 'SAN', 'Técnico en Emergencias Sanitarias', 'G.M.'),
('FAPA2', 'SAN', 'Técnico en Farmacia y Parafarmacia', 'G.M.'),
('HIGBU3', 'SAN', 'Técnico Superior en Higiene Bucodental', 'G.S.'),
('IDMN3', 'SAN', 'Técnico Superior en Imagen para el Diagnóstico y Medicina Nuclear', 'G.S.'),
('LACB3', 'SAN', 'Técnico Superior en Laboratorio Clínico y Biomédico', 'G.S.'),
('OPAP3', 'SAN', 'Técnico Superior en Ortoprótesis y Productos de Apoyo', 'G.S.'),
('PRDE3', 'SAN', 'Técnico Superior en Prótesis Dentales', 'G.S.'),
('RADO3', 'SAN', 'Técnico Superior en Radioterapia y Dosimetría', 'G.S.'),
('CEPC3', 'SEA', 'Técnico Superior en Coordinación de Emergencias y Protección Civil', 'G.S.'),
('EDCA3', 'SEA', 'Técnico Superior en Educación y Control Ambiental', 'G.S.'),
('EPCI2', 'SEA', 'Técnico en Emergencias y Protección Civil', 'G.M.'),
('QSAM3', 'SEA', 'Técnico Superior en Química y Salud Ambiental', 'G.S.'),
('ADLE1', 'SSC', 'Profesional Básico en Actividades Domésticas y Limpieza de Edificios', 'BÁSICA'),
('ASTU3', 'SSC', 'Técnico Superior en Animación Sociocultural y Turística', 'G.S.'),
('EDIN3', 'SSC', 'Técnico Superior en Educación Infantil', 'G.S.'),
('FMSS3', 'SSC', 'Técnico Superior en Formación para la Movilidad Segura y Sostenible', 'G.S.'),
('INSO3', 'SSC', 'Técnico Superior en Integración Social', 'G.S.'),
('MECO3', 'SSC', 'Técnico Superior en Mediación Comunicativa', 'G.S.'),
('PESD2', 'SSC', 'Técnico en Atención a Personas en Situación de Dependencia', 'G.M.'),
('PIGG3', 'SSC', 'Técnico Superior en Promoción de Igualdad de Género', 'G.S.'),
('ARRE1', 'TCP', 'Profesional Básico en Arreglo y Reparación de Artículos Textiles y de Piel', 'BÁSICA'),
('CACM2', 'TCP', 'Técnico en Calzado y Complementos de Moda', 'G.M.'),
('COMO2', 'TCP', 'Técnico en Confección y Moda', 'G.M.'),
('DPCC3', 'TCP', 'Técnico Superior en Diseño y Producción de Calzado y Complementos', 'G.S.'),
('DTTP3', 'TCP', 'Técnico Superior en Diseño Técnico en Textil y Piel', 'G.S.'),
('FEPT2', 'TCP', 'Técnico en Fabricación y Ennoblecimiento de Productos Textiles', 'G.M.'),
('PAMO3', 'TCP', 'Técnico Superior en Patronaje y Moda', 'G.S.'),
('TACO1', 'TCP', 'Profesional Básico en Tapicería y Cortinaje', 'BÁSICA'),
('VMES3', 'TCP', 'Técnico Superior en Vestuario a Medida y de Espectáculos', 'G.S.'),
('APDR3', 'TMV', 'Curso de Especialización en Aeronaves Pilotadas de Forma Remota-Drones', 'C.E. (G.S.)'),
('AUTO3', 'TMV', 'Técnico Superior en Automoción', 'G.S.'),
('CARR2', 'TMV', 'Técnico en Carrocería', 'G.M.'),
('CVTC2', 'TMV', 'Técnico en Conducción de Vehículos de Transporte por Carretera', 'G.M.'),
('ELMA2', 'TMV', 'Técnico en Electromecánica de Maquinaria', 'G.M.'),
('ELVA2', 'TMV', 'Técnico en Electromecánica de Vehículos Automóviles', 'G.M.'),
('MAAP3', 'TMV', 'Técnico Superior en Mantenimiento Aeromecánico de Aviones con Motor de Pistón', 'G.S.'),
('MAAT3', 'TMV', 'Técnico Superior en Mantenimiento Aeromecánico de Aviones con Motor de Turbina', 'G.S.'),
('MAER2', 'TMV', 'Técnico en Mantenimiento de Embarcaciones de Recreo', 'G.M.'),
('MAHP3', 'TMV', 'Técnico Superior en Mantenimiento Aeromecánico de Helicópteros con Motor de Pistón', 'G.S.'),
('MAHT3', 'TMV', 'Técnico Superior en Mantenimiento Aeromecánico de Helicópteros con Motor de Turbina', 'G.S.'),
('MAMR3', 'TMV', 'Curso de Especialización en Mantenimiento Avanzado de Sistemas De Material Rodante Ferroviario', 'C.E. (G.S.)'),
('MAVE1', 'TMV', 'Profesional Básico en Mantenimiento de Embarcaciones Deportivas y de Recreo', 'BÁSICA'),
('MEDR1', 'TMV', 'Profesional Básico en Mantenimiento de Vehículos', 'BÁSICA'),
('MEME2', 'TMV', 'Técnico en Mantenimiento de Estructuras de Madera y Mobiliario de Embarcaciones de Recreo', 'G.M.'),
('MESA2', 'TMV', 'Técnico en Montaje de Estructuras e Instalación de Sistemas Aeronáuticos', 'G.M.'),
('MMRF2', 'TMV', 'Técnico en Mantenimiento de Material Rodante Ferroviario', 'G.M.'),
('MSEA3', 'TMV', 'Técnico Superior en Mantenimiento de Sistemas Electrónicos y Aviónicos en Aeronaves', 'G.S.'),
('MVHE2', 'TMV', 'Curso de Especialización en Mantenimiento de Vehículos Híbridos y Eléctricos', 'C.E. (G.M.)'),
('SVHE3', 'TMV', 'Curso de Especialización en Mantenimiento y Seguridad en Sistemas de Vehículos Híbridos y Eléctricos', 'C.E. (G.S.)'),
('DFPC3', 'VIC', 'Técnico Superior en Desarrollo y Fabricación de Productos Cerámicos', 'G.S.'),
('FAPC2', 'VIC', 'Técnico en Fabricación de Productos Cerámicos', 'G.M.'),
('VIAL1', 'VIC', 'Profesional Básico en Vidriería y Alfarería', 'BÁSICA');
COMMIT;
SET foreign_key_checks=1;